name: Build and Deploy GitHub Pages Test

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "â˜ï¸ checkout repository"
        uses: actions/checkout@v2

      - name: "ğŸ”§ setup node"
        uses: actions/setup-node@v2
        with:
          node-version: 14 

      - name: "ğŸ“¦ install dependencies and build project"
        run: |
          echo "Install backend..."
          cd server
          npm install
          npm run build
      - name : "ğŸ“‚ Upload artifact"
        uses: actions/upload-artifact@v2
        with:
          name : build
          path : build
  deploy:
    name: "ğŸš€ Deploy App to Azure WebApp"
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 10
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps : 
      - name: "ğŸ“‚ download build artifacts"
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      # - name: "ğŸš€ Deploy to Azure Static Web Apps"
      #   uses: Azure/static-web-apps-deploy@v1
      #   with:
      #     azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     app_location: "server/build"  
      #     api_location: "server/api"           



