name: Build and Deploy App

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    name : "ğŸ”§ Build App"
    runs-on: ubuntu-latest

    steps:
      - name: "â˜ï¸ checkout repository"
        uses: actions/checkout@v2

      - name: "ğŸ”§ setup node"
        uses: actions/setup-node@v2
        with:
          node-version: '18.x' 

      - name: "ğŸ“¦ install dependencies and build project"
        run: |
          echo "Install backend..."
          cd server
          npm install
          npm run build
      - name : "ğŸ“‚ Upload artifact"
        uses: actions/upload-artifact@v2
        with:
          name : combined-build
          path : .
          # path : server/combined-build
  deploy:
    name: "ğŸš€ Deploy App to Azure WebApp"
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 10
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps : 
      - name: "ğŸ“‚ download build artifacts"
        uses: actions/download-artifact@v2
        with:
          name: combined-build
          path: server/combined-build
      - name: 'ğŸš€ Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'shoppingonline-1'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_550AED0E063344B4BD7B44C687DA6A7A }}
          package: .




